### ISSUE TITLE
Our-services

### ISSUE THREAD

**Issue by Lmise** [Podiihq/podiihq#30]
-Change icon and icon size
-Replace lorem ipsum with podii's services details
-Change fonts.

**Comment by Krafty-Coder** [comment]
# Current view on desktop

## Done 
 - Changed icons and their sizes
 - Replaced lorem with content on the site

![Screenshot from 2018-04-12 12-38-09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a9ae8cf01903c001175422e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b168ee10365257424ea553444d04bea6d37ef5f22e7a98595abe853c0d27c03f47acb98017bf01bb748a1a8ce4b58b5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af54ee44556ac123164e7647b.png)

**Comment by Krafty-Coder** [comment]
This was a mistake and the issue is on review
